services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "8888:80"
    depends_on:
      - api-server
      - honox
    restart: unless-stopped

  honox:
    build:
      context: ./honox
      dockerfile: Dockerfile
    container_name: honox
    ports:
      - "38888:3000"
    depends_on:
      - api-server
    restart: unless-stopped

  api-server:
    build:
      context: ./api-server
      dockerfile: Dockerfile
    container_name: api-server
    ports:
      - "38080:8080"
    restart: unless-stopped
