services:
  nginx:
    build:
      context: . # honox がビルドする内容を参照するため、カレントディレクトリを指定
      dockerfile: ./nginx/Dockerfile
    container_name: nginx
    ports:
      - "8888:80"
    depends_on:
      - api-server
      - honox
    restart: unless-stopped

  honox:
    build:
      context: ./honox
      dockerfile: Dockerfile
    container_name: honox
    expose:
      - 3000
    depends_on:
      - api-server
    restart: unless-stopped

  api-server:
    build:
      context: ./api-server
      dockerfile: Dockerfile
    container_name: api-server
    expose:
      - 8080
    restart: unless-stopped
